version: '3.2'

networks:
  demo54:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.18
    container_name: mysql
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./config/mysql:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - demo54
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    ports:
      - 3307:9104
    environment:
      - DATA_SOURCE_NAME=root:123456@tcp(mysql:3306)/
    volumes:
      - ./config/mysql-exporter/my.cnf:/etc/mysql/my.cnf
    command:
      - --config.my-cnf=/etc/mysql/my.cnf
    depends_on:
      - mysql
    networks:
      - demo54
  redis:
    container_name: redis
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    networks:
      - demo54
  redis-exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
      - 6380:9121
    networks:
      - demo54
    depends_on:
      - redis
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - 9101:9100
    networks:
      - demo54
  rmqnamesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
    networks:
      - demo54
  rmqbroker:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./config/rocketmq/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    depends_on:
      - rmqnamesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
    networks:
      - demo54
  rmq-exporter:
    image: admin4j/rocketmq-exporter
    container_name: rmq-exporter
    command:
      - /bin/sh
      - -c
      - /usr/bin/java -Djava.security.egd=file:/dev/./urandom $JVM_OPT -jar quickstart.jar --rocketmq.config.namesrvAddr="rmqnamesrv:9876"
    ports:
      - 5557:5557
    networks:
      - demo54
    depends_on:
      - rmqnamesrv
  process_exporter:
    image: zhaoy1216/process_exporter
    container_name: process_exporter
    privileged: true
    volumes:
      - /proc:/proc
      - ./config/process_exporter/process_exporter.yml:/etc/process_exporter.yml
    entrypoint: /bin/process-exporter -config.path=/etc/process_exporter.yml
    ports:
      - 9256:9256
    networks:
      - demo54
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/hosts:/etc/hosts
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 9090:9090
    networks:
      - demo54
  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    networks:
      - demo54
    depends_on:
      - prometheus
