{
 "title": "Named processes by host",
 "description": "Process metrics exported by https://github.com/ncabatoff/process-exporter.\r\n",
 "tags": [
  "OS",
  "Linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(namedprocess_scrape_errors, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "number of processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{groupname=~\"$processes\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\"}[$interval])",
     "legendFormat": "{{groupname}} ({{mode}})"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\"}[$interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}